###
# API Book

@baseUrl = http://localhost

### Get Book 1
GET {{baseUrl}}/books/1
Accept: application/json

### Get Book 2
GET {{baseUrl}}/books/2
Accept: application/json

### Get Book 3
GET {{baseUrl}}/books/3
Accept: application/json

### Get Book 4
GET {{baseUrl}}/books/4
Accept: application/json

