services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  books:
    build:
      context: .
      args:
        - SPRING_JAR=app-books-server-1.0.0.jar
    ports:
      - 9999:9999
    deploy:
      replicas: 1
  store:
    build:
      context: .
      args:
        - SPRING_JAR=app-store-server-1.0.0.jar
    depends_on:
      books:
        condition: service_healthy
