services:
  books:
    container_name: io-example-books
    build:
      context: .
      args:
        - SPRING_JAR=app-books-server-1.0.0.jar
    ports:
      - 9001:8080
  store:
    container_name: io-example-store
    build:
      context: .
      args:
        - SPRING_JAR=app-store-server-1.0.0.jar
    ports:
      - 9002:8080
    depends_on:
      books:
        condition: service_healthy
